
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 13;
  public static final int PREFIX = 10;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int IF = 8;
  public static final int ELSE = 9;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int RCURLY = 6;
  public static final int RPAREN = 4;
  public static final int IDENTIFIER = 12;
  public static final int LPAREN = 3;
  public static final int LCURLY = 5;
  public static final int REVERSE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "COMMA",
  "IF",
  "ELSE",
  "PREFIX",
  "REVERSE",
  "IDENTIFIER",
  "STRING_LITERAL"
  };
}

